/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab1.exercises.views;

import lab1.exercises.exercise2.StockStat;

/**
 *
 * @author miccarurb
 */
public class Punto2 extends javax.swing.JFrame {

    /**
     * Creates new form Punto2
     */
    public Punto2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtResupplyPeriod = new javax.swing.JTextField();
        txtCurrentAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAverageUsed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMinUsedDaily = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaxUsedDaily = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMinAmount = new javax.swing.JTextField();
        txtMaxAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtOrderPoint = new javax.swing.JTextField();
        txtOrderAmount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consumo Medio Diario.");

        txtResupplyPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResupplyPeriodActionPerformed(evt);
            }
        });

        txtCurrentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentAmountActionPerformed(evt);
            }
        });

        jLabel2.setText("Tiempo de Reposicion de Inventario:");

        txtAverageUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAverageUsedActionPerformed(evt);
            }
        });

        jLabel3.setText("Existencia Actual:");

        txtMinUsedDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinUsedDailyActionPerformed(evt);
            }
        });

        jLabel5.setText("Consumo Mínimo Diario");

        jLabel6.setText("Consumo Maximo Diario");

        txtMaxUsedDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxUsedDailyActionPerformed(evt);
            }
        });

        jLabel7.setText("Existencia Minima");

        txtMinAmount.setEditable(false);
        txtMinAmount.setBackground(new java.awt.Color(102, 153, 255));
        txtMinAmount.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtMinAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinAmountActionPerformed(evt);
            }
        });

        txtMaxAmount.setEditable(false);
        txtMaxAmount.setBackground(new java.awt.Color(102, 153, 255));
        txtMaxAmount.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtMaxAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxAmountActionPerformed(evt);
            }
        });

        jLabel8.setText("Existencia Maxima");

        jLabel9.setText("Punto de Pedido");

        txtOrderPoint.setEditable(false);
        txtOrderPoint.setBackground(new java.awt.Color(102, 153, 255));
        txtOrderPoint.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtOrderPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderPointActionPerformed(evt);
            }
        });

        txtOrderAmount.setEditable(false);
        txtOrderAmount.setBackground(new java.awt.Color(102, 153, 255));
        txtOrderAmount.setToolTipText("");
        txtOrderAmount.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtOrderAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderAmountActionPerformed(evt);
            }
        });

        jLabel10.setText("Cantidad de Pedido");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setAlignmentY(0.0F);
        lblError.setMaximumSize(new java.awt.Dimension(51, 30));
        lblError.setMinimumSize(new java.awt.Dimension(5, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOrderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAverageUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResupplyPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinUsedDaily, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaxUsedDaily, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrderPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jLabel2)
                    .addContainerGap(396, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(txtResupplyPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurrentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAverageUsed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtMinUsedDaily, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtMaxUsedDaily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMinAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrderPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jLabel2)
                    .addContainerGap(452, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResupplyPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResupplyPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResupplyPeriodActionPerformed

    private void txtCurrentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentAmountActionPerformed

    private void txtAverageUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAverageUsedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAverageUsedActionPerformed

    private void txtMinUsedDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinUsedDailyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinUsedDailyActionPerformed

    private void txtMaxUsedDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxUsedDailyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxUsedDailyActionPerformed

    private void txtMinAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinAmountActionPerformed

    private void txtMaxAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxAmountActionPerformed

    private void txtOrderPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderPointActionPerformed

    private void txtOrderAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderAmountActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        lblError.setText("");
        try{
            int resupplyPeriod = Integer.parseInt(txtResupplyPeriod.getText());
            float averageUsed = Float.parseFloat(txtAverageUsed.getText());
            float currentAmount = Float.parseFloat(txtCurrentAmount.getText());
            float minUsedDaily = Float.parseFloat(txtMinUsedDaily.getText());
            float maxUsedDaily = Float.parseFloat(txtMaxUsedDaily.getText());

            StockStat stock = new StockStat(resupplyPeriod, currentAmount, averageUsed, maxUsedDaily, minUsedDaily);
            stock.calcAll();
            txtMinAmount.setText(String.valueOf(stock.getMinAmount()));
            txtMaxAmount.setText(String.valueOf(stock.getMaxAmount()));
            txtOrderPoint.setText(String.valueOf(stock.getOrderPoint()));
            txtOrderAmount.setText(String.valueOf(stock.getOrderAmount()));
            
        }catch(Exception e){
            lblError.setText("Ocurrió un error");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Punto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Punto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Punto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Punto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Punto2().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtAverageUsed;
    private javax.swing.JTextField txtCurrentAmount;
    private javax.swing.JTextField txtMaxAmount;
    private javax.swing.JTextField txtMaxUsedDaily;
    private javax.swing.JTextField txtMinAmount;
    private javax.swing.JTextField txtMinUsedDaily;
    private javax.swing.JTextField txtOrderAmount;
    private javax.swing.JTextField txtOrderPoint;
    private javax.swing.JTextField txtResupplyPeriod;
    // End of variables declaration//GEN-END:variables
}
